### ISSUE TITLE
Cross-platform web configurator

### ISSUE THREAD

**Issue by Fortinbra** [OpenStickFoundation/GP2040-CE#10]

**Comment by henrebotha** [comment]
Related issue on the upstream: https://github.com/FeralAI/GP2040/issues/43

**Comment by davewongillies** [comment]
This probably isn't of much help, but I noticed that whatever is going on with this firmware, rndis & the Linux kernel, that it makes Linux unhappy enough that I can't even do USB pass through to a Windows VM in Virtualbox (that's a first for me). That's even with the rndis kernel modules blacklisted.

**Comment by TheTrainGoes** [comment]
This has been resolved, updates coming out soon

**Comment by TheTrainGoes** [comment]
Thought we had merged this already - reopening

**Comment by TheTrainGoes** [comment]
Waiting on the CMake changes then we should be able to get this closed out.  Will re-make on the new GitHub
