### ISSUE TITLE
how do you use LEDs?

### ISSUE THREAD

**Issue by jojo22904** [OpenStickFoundation/GP2040-CE#123]
I'm gonna ask a dumb question because I'm new to all of this. But I've got a very simple controller setup and I can't find anywhere that tells you how to set up LEDs. If anyone could help that would be great. Like I said I'm new to this stuff so sorry if that's a dumb question. thanks!

**Comment by TheTrainGoes** [comment]
Hey @jojo22904 ,

No stupid questions, we all started somewhere with this stuff.  

If you want to hop on our Discord we can walk you though setting up LEDs.

**Comment by jojo22904** [comment]
Hey do you mind if I start a discussion on GitHub instead? I don't really use discord

**Comment by TheTrainGoes** [comment]
Hey @jojo22904 ,

No problem, might just take a bit longer to get back to replies.

Which LEDs are you trying to use with the setup?  If you have an image of what you are working with please attach it.

**Comment by jojo22904** [comment]
@TheTrainGoes 

I started a discussion and answered your questions there thank you so much for your help

**Comment by TheTrainGoes** [comment]
Answered in the discussions section
