### ISSUE TITLE
Brook Wingman Question

### ISSUE THREAD

**Issue by raion21** [OpenStickFoundation/GP2040-CE#142]
Will this work with a Brook Wingman on the PS4/PS5 if it's on Xinput mode or any of the other modes for that matter? Will there be any additional input delay from this?

**Comment by TheTrainGoes** [comment]
Hey @raion21 ,

There have been reports that this works on the Brook Wingman on PS4 and PS5.  We are not sure if this will be compatible with the new PS5 converter that Brook is working on though.  

Input delay wise there is a tiny amount added but it is nothing significant.
