### ISSUE TITLE
Reversed mixbox layout for OLED

### ISSUE THREAD

**Issue by luisvoo** [OpenStickFoundation/GP2040-CE#148]
Hi, I am finding a way to get a reversed layout for the OLED. the picture attached is the layout I hope to achieve

![LAYOUT](https://user-images.githubusercontent.com/94888012/202439507-0e9306f0-0d37-4b19-9a4e-7b738ff09bf8.jpg)

**Comment by TheTrainGoes** [comment]
I should be able to get this done for you.  When I have a bit of time I will take a swing at it.

**Comment by luisvoo** [comment]
> I should be able to get this done for you. When I have a bit of time I will take a swing at it.

Thank you, I look forward to it!

**Comment by TheTrainGoes** [comment]
Closing here, will re-open on the new GitHub if still wanted
