### ISSUE TITLE
Can you run Dpad and LeftStick Together (dual directional) ?

### ISSUE THREAD

**Issue by travmaa** [OpenStickFoundation/GP2040-CE#172]
Hello All, I want to do a dual directional. For this I need to run the left stick (emulate 4pin) and dpad at the same time, I couldn't do it, can anyone do it ?
I want it to be with the original crossup logic.
4pin dpad input
4pin left stick input is switched not resistive
with socd modes , direct input, xinput, switch modes
rp2040 or atmega32u4
ty.

**Comment by TheTrainGoes** [comment]
This is being worked on by @arntsonl

**Comment by TheTrainGoes** [comment]
This was completed
