### ISSUE TITLE
I just have a question. I know this is supposed to work with brook wingman adapters but does anyone know if it works with mayflash adapters? Thanks!

### ISSUE THREAD

**Issue by jojo22904** [OpenStickFoundation/GP2040-CE#177]

**Comment by TheTrainGoes** [comment]
Hi @jojo22904 ,

I am not sure if anyone here has one to test it on.  

We have also moved over to another GitHub space.  If you would like, please re-post this to:
https://github.com/OpenStickCommunity/GP2040-CE/issues

Also feel free to join the Discord, someone there may have one to test it on.
