### ISSUE TITLE
Current source does not build due to WizIO change

### ISSUE THREAD

**Issue by mxd1365** [OpenStickFoundation/GP2040-CE#28]
Due to this update to tinyUSB inside of Wiz-IO (https://github.com/Wiz-IO/framework-wizio-pico/commit/dbbbddaf54003e881f50d97a49d61b454aa5696d), the current version of GP2040-CE does not build.

The work around is to hard reset locally to this commit: https://github.com/Wiz-IO/framework-wizio-pico/commit/9fd8b5abae37924cdd48737f4406df0ab79ce183

**Comment by TheTrainGoes** [comment]
Closing this issue as the fix provided by @arntsonl has been tested and works.
