### ISSUE TITLE
Display freezes after a few seconds

### ISSUE THREAD

**Issue by butterrsoft** [OpenStickFoundation/GP2040-CE#30]
Hi, i have an SSD1306 128x64 OLED display, and it freezes about 10 seconds the stick is plugged in. Hot-plugging the OLED makes it work for another ten seconds or so. 

Also, after powering down the stick, if i plug it back in right away the display rarely comes up. Hot-plugging the OLED does nothing there.

I have a couple more OLEDs on order from another seller and will try to figure out if the display itself is the issue.

**Comment by butterrsoft** [comment]
Actually, on longer testing, sometimes the display comes to life again, and freezes again, and comes to life again, and repeat.

**Comment by TheTrainGoes** [comment]
Hi @butterrsoft ,

Can you link the specific OLED that you are using?  I have run into some issues with OLEDs from Amazon and AliExpress.

**Comment by butterrsoft** [comment]
This one from Aliexpress - https://www.aliexpress.com/item/32233334632.html?spm=a2g0o.order_list.0.0.6a181802U0pJZs

I have a couple more on order that actually say they have the ssd1306 chip in them, but they're probably the same.

**Comment by TheTrainGoes** [comment]
Hi @butterrsoft ,

Feel free to join the OpenStick Discord if you would like to have a more in-depth chat about this.  

Can you confirm which IIC address is selected on the back of the OLED and also what your display settings are currently set at in the online config tool?

**Comment by TheTrainGoes** [comment]
Closing this as we have not been able to reproduce the issue via any configuration and consider this a hardware issue.  Will re-open if we can reproduce.

**Comment by TheTrainGoes** [comment]
We have confirmed that this was a bad OLED module.
