### ISSUE TITLE
Support for the Waveshare RP2040 Zero

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickFoundation/GP2040-CE#32]
The Waveshare RP2040 Zero (found here: https://www.waveshare.com/rp2040-zero.htm) is a small Pico clone that offers enough GPIO pins for a basic setup.  

I will likely take this request on and create a firmware that can be used for it.

**Comment by TheTrainGoesChoo** [comment]
This has been done compiled and tested.  Once we move to .44 I will submit a PR with the changes and merge.

**Comment by TheTrainGoes** [comment]
This has been done compiled and tested. Once we move to .44 I will submit a PR with the changes and merge.

**Comment by TheTrainGoes** [comment]
Added in https://github.com/OpenStickFoundation/GP2040-CE/pull/105

Will test tomorrow and merge

**Comment by TheTrainGoes** [comment]
Done and merged
