### ISSUE TITLE
Update to screen display layout while in web-config mode

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickFoundation/GP2040-CE#42]
With v0.5.0 the screen now fully changes when in web-config mode.  

I am recommending that we keep the top row of information visible while in web-config mode and simply replace the joystick layout graphics with the the notice that you are in web-config mode.

**Comment by arntsonl** [comment]
Agreed, new code will have status bar and web config mode text, plus the GP2040 version.

**Comment by arntsonl** [comment]
Fixed in 0.5.1 release.
