### ISSUE TITLE
Update to the web-config information on the OLED

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickFoundation/GP2040-CE#47]
Currently, when in web-config mode and while an OLED is connected you will get a notice in place of the buttons.  

Should we have this centred on the screen over left justification?

**Comment by arntsonl** [comment]
Yeah that's totally fine! I thought it would be a nice little message and it would help us debug when folks say they can't get debug working.

I'll add this to my to-dos

**Comment by TheTrainGoes** [comment]
Love the feature!  This is a really good way to know when the RP2040 is in web-config mode.

**Comment by TheTrainGoes** [comment]
This has been updated.
