### ISSUE TITLE
Update `BUTTON_LAYOUT` to `BUTTON_LAYOUT_LEFT`

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickFoundation/GP2040-CE#51]
`BUTTON_LAYOUT` is now a legacy name since the introduction of additional layouts for the right side buttons listed as `BUTTON_LAYOUT_RIGHT`.

From:

`BUTTON_LAYOUT`

To:

`BUTTON_LAYOUT_LEFT`

**Comment by arntsonl** [comment]
This is in latest, will close once we release the next version.
