### ISSUE TITLE
Abandon PlatformIO

### ISSUE THREAD

**Issue by henrebotha** [OpenStickFoundation/GP2040-CE#65]
There has been some discussion around getting away from PlatformIO. Doing so would also allow us to drop the dependency on wizio-pico.

Moving away from PlatformIO probably means adopting CMake instead.

There are apparently some breaking changes in the latest Pico SDK, so we'd need to accommodate those in the migration. (Could we instead target whichever SDK version PlatformIO currently targets, just to ease the migration off of PlatformIO? We could always migrate first, then upgrade.)

**Comment by TheTrainGoes** [comment]
Closing here, will re-open on the new GitHub if still wanted
