### ISSUE TITLE
Turbo Button Support

### ISSUE THREAD

**Issue by Fortinbra** [OpenStickFoundation/GP2040-CE#7]

**Comment by arntsonl** [comment]
I'm taking this one

**Comment by TheTrainGoes** [comment]
This has been implemented in the PicoAnn firmware that is available here:
https://github.com/alirin222/GP2040-PicoAnn

I have tested this firmware and it works as intended including the additions to the OLED.

It is recommended that we find a solution which does not require the use of GPIO25 (TP) for the Turbo LED.

**Comment by arntsonl** [comment]
Done and in the official v0.5.0 release!
