### ISSUE TITLE
Add "game mode" configuration

### ISSUE THREAD

**Issue by nullczek** [OpenStickFoundation/GP2040-CE#77]
Right now, you can switch backends in config for xinput, switch, etc.
Settings in config are either global or specific to the backend.

Add a higher level container, the "game mode" profile for settings to contain all settings and setting overrides, that will contain all settings for a specific game or genre, as defined by the user. Being able to import/export these would be great for sharing configs with other people or other gp2040 devices.

The container can contain overrides for button mappings, LED settings, OLED layout etc, SOCD behavior, Macros, etc, as these will largely be game or genre specific.
This is similar to what HayBox does, except with a UI.

display should show what profile is used.

maybe remeber last used profile on power on.

**Comment by TheTrainGoes** [comment]
Closing here, will re-open on the new GitHub if still wanted
