### ISSUE TITLE
Analog (ADC pins) configuration in Web-Config

### ISSUE THREAD

**Issue by arntsonl** [OpenStickFoundation/GP2040-CE#82]
Add the Analog ADC pins to the web-config add-ons page.

This will allow adding the analog support without having to recompile the firmware.

**Comment by Shambler2** [comment]
Hi! Wondering if this feature is nearing release? If not - what's the best way to read in analog input for example for a analog trigger? Found mentions of support on pin 26/7 (ADC0/1) but can't see how to enable it yet or map it to a specific input

**Comment by TheTrainGoes** [comment]
This was added as part of https://github.com/OpenStickFoundation/GP2040-CE/pull/129
