### ISSUE TITLE
Use board version from board flash rather than hard-coded in Web-UI

### ISSUE THREAD

**Issue by arntsonl** [OpenStickFoundation/GP2040-CE#83]
The board version is currently hard-coded in the React code, but it is now included in the flash memory of the board options.

Instead, this should be pulled from the board options on load of the main page.

This will help with updates later and weird mid-version issues.

**Comment by deeebug** [comment]
As mentioned in the PR, please see and merge.

Thank you.

**Comment by arntsonl** [comment]
Fixed with PR #164
