### ISSUE TITLE
Move splash screen to new EEPROM memory location & add to Web-UI

### ISSUE THREAD

**Issue by arntsonl** [OpenStickFoundation/GP2040-CE#84]
Splash screen is currently hardcoded in bitmaps.h

Move this to an EEPROM memory location and add the ability to upload new 1bpp images to the web-UI.

Web-UI will need to decide if it takes a raw binary file, or if you can input something like:

0xFF,0xFF,0xCA.... 

to make life easier for anyone wanting to change the screens.

We either want to implement an RLE compression, or make sure we allocate 1KB for the splash screen.

**Comment by deeebug** [comment]
Hello, this is how it looks like. I hope that it's good enough for now.
![image](https://user-images.githubusercontent.com/77402236/204154729-26c7f5cc-4467-41c1-a31e-c1a163427d37.png)
